version: "3.8"
networks:
  network_datastream:
services:
  postgresql_datastream:
    image: postgres
    build: ./postgres/dataDatastream
    container_name: datastream_db
    restart: always
    environment:
      POSTGRES_DB: datastream_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432  
    volumes:
      - ./postgres/dataDatastream:/var/lib/postgresql/dataDatastream
    networks:
      - network_datastream
  postgresql_cogesaf:
    image: postgres
    build: ./postgres/dataCogesaf
    container_name: cogesaf_db
    restart: always
    environment:
      POSTGRES_DB: cogesaf_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432  
    volumes:
      - ./postgres/dataCogesaf:/var/lib/postgresql/dataCogesaf
    networks:
      - network_datastream